### ISSUE TITLE
The last commit messed up the main method

### ISSUE THREAD

**Issue by arieldiego73** [MinaSeulgi/IPT2-CaseStudy#6]
### Pull Request #5 
The latest method `askForToppingQuantity` is located inside the `main` method but this should not be the proper way of writing it. Fix the issue and do another commit, @MinaSeulgi.

**Comment by MinaSeulgi** [comment]
#12 This issue is fixed on this recent pull request @arieldiego73 .
Thank you!

**Comment by arieldiego73** [comment]
Thanks!
